name: Testing, Checking & Formatting
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - run: npm test

  lint:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint

  pretty:
    name: Prettify
    runs-on: ubuntu-latest
    steps:
      - run: npm run format

